language: node_js

node_js:
  - master

branches:
  only:
    - master

script:
  - npm i -g standard-version

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@opale.net"
  - git remote add upstream "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - git fetch upstream
  - standard-version
  - git push --follow-tags upstream master
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - git-chglog $PREVIOUS_TAG..$TRAVIS_TAG --no-case > /home/travis/changelog.tmp.md

deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  cleanup: false
  draft: true
  name: $TRAVIS_TAG
  release_notes_file: /home/travis/changelog.tmp.md
