language: go

cache:
  directories:
    - /usr/local/go
    - $HOME/go

go:
  - master

install:
  - go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  - export PATH=$PATH:~/go/bin

script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@opale.net"
  - git remote add upstream "https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - git fetch upstream
  - git checkout -b changelog-tci
  - git-chglog --next-tag mytag --output CHANGELOG.md --no-case
  - git add -A CHANGELOG.md
  - git commit -m "updated changelog"
  - git push https://opalenet-adrien:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git HEAD:changelog-tci
