language: go

go:
  - master

before_script:
  - go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  - export PATH=$PATH:~/go/bin

script:
  - git-chglog --next-tag mytag --output CHANGELOG.md --no-case

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@opale.net"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: "CHANGELOG.md"
  skip_cleanup: true
  draft: true
