language: go

go:
  - master

before_script:
  - go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  - export PATH=$PATH:~/go/bin

script:
  - export PREVIOUS_TAG=$(git describe --abbrev=0 --tags)
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}

before_deploy:
  # Set up git user name and tag this commit
  - tar -czvf /home/travis/$TRAVIS_TAG.tar.gz ./
  - zip -r /home/travis/$TRAVIS_TAG.zip ./
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@opale.net"
  - git remote add upstream "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - git fetch upstream
  - git checkout -b changelog-tci
  - git-chglog --next-tag $TRAVIS_TAG --output CHANGELOG.md --no-case
  - git add -A CHANGELOG.md
  - git commit -m "updated changelog at ${rev}"
  - git push upstream changelog-tci
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - git-chglog $PREVIOUS_TAG..$TRAVIS_TAG --no-case > /home/travis/changelog.tmp.md

deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  file_glob: true
  file:
    - /home/travis/$TRAVIS_TAG.tar.gz
    - /home/travis/$TRAVIS_TAG.zip
  cleanup: false
  draft: true
  name: $TRAVIS_TAG
  release_notes_file: /home/travis/changelog.tmp.md
  on:
    branch: master
