language: go

cache:
  directories:
    - /usr/local/go
    - $HOME/go

go:
  - master

install:
  - git config user.name "Travis CI"
  - git config user.email "travis-ci@opale.net"
  - go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  - export PATH=$PATH:~/go/bin

script:
  - git-chglog --next-tag mytag --output CHANGELOG.md
  - git checkout -b changelog-tci
  - git push --set-upstream origin changelog-tci
  - git add CHANGELOG.md
  - git commit -m "updated changelog"
  - git push
