language: node_js

node_js:
  - lts/*

branches:
  only:
    - master

script:
  - npm i -g standard-version

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@opale.net"
  - git remote add upstream "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - git fetch upstream
  - standard-version -i /home/travis/changelog.tmp.md --skip.commit --skip.tag
  - standard-version --skip.commit
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(git describe --abbrev=0 --tags)}
  - git add -A CHANGELOG.md
  - git commit -m "chore(release):Update CHANGELOG.md for $TRAVIS_TAG"
  - git push --follow-tags upstream master

deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  cleanup: false
  draft: true
  name: $TRAVIS_TAG
  release_notes_file: /home/travis/changelog.tmp.md
