language: go

cache:
  directories:
    - /usr/local/go
    - $HOME/go

go:
  - master

install:
  - git config user.name "Travis CI"
  - git config user.email "travis-ci@opale.net"
  - go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
  - export PATH=$PATH:~/go/bin

script:
  - git remote add upstream "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - git fetch upstream
  - git checkout changelog-tci
  - git-chglog --next-tag mytag --output CHANGELOG.md --no-case
  - git add CHANGELOG.md
  - git commit -m "updated changelog"
  - git push upstream changelog-tci
