version: "3"

services:
  benchmark:
    image: php:latest
    volumes:
      - ./:/app/
      - ~/.bashrc:/root/.bashrc
      - ~/.bash-git-prompt/:/root/.bash-git-prompt/
      - ~/.ssh/:/root/.ssh/
      - ~/.git/:/root/.git/
    tty: true
    restart: always
