bin: git
style: ''
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/adynemo/odl
options:
  commits:
    filters:
      Type:
        # Update for changes in existing functionality.
        # feat for new features.
        # Changed for changes in existing functionality.
        # Deprecated for soon-to-be removed features.
        # Removed for now removed features.
        # fix for any bug fixes.
        # Security in case of vulnerabilities.
        # https://keepachangelog.com/en/1.0.0/
        - add
        - merge
        - fix
        - update
        - remove
  commit_groups:
    group_by:
    sort_by: Scope
    title_maps:
      remove: 'Remove'
      add: 'Features'
      fix: 'Fixes'
      update: 'Update'
      uerge: 'Merge'

  header:
    pattern: "^(\\w*)\\s\\s?(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
