#default
# If you want to customize this file, change 'default' to anything else on the first line
name: Changelog & Release

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install git
        run: |
          sudo apt update
          sudo apt install -y git
      - name: Config git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@opale.net"
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install standard-version
        run: npm i -g standard-version
      - name: Update repository
        run: |
          git fetch --tags
          git pull --unshallow
          git tag > /tmp/tags
          echo "TAGS=$(tr -d "\n" < /tmp/tags)" >> $GITHUB_ENV
      - name: Generate first changelog
        if: ${{ env.TAGS == 0 }}
        run: |
          standard-version --first-release -i /tmp/changelog.tmp.md --skip.commit --skip.tag
          standard-version --first-release
          echo "TAG_NAME=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Generate changelog
        if: ${{ env.TAGS != 0 }}
        run: |
          standard-version -i /tmp/changelog.tmp.md --skip.commit --skip.tag
          standard-version
          echo "TAG_NAME=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Publish changelog
        run: git push --follow-tags origin ${{ github.base_ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body_path: /tmp/changelog.tmp.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
